language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    # - pypy
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install ipaddress unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install ipaddress; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install ipaddress; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install ipaddress; fi
script:
    - pip install flake8
    - python setup.py build
    - python setup.py install
    - python test/test_psutil.py
    - python test/test_memory_leaks.py
    - make flake8
os:
    - linux
    - osx

